sudo: false
language: node_js
node_js:
    - 0.12
    - 4
    - stable
env:
  - CHAI_VERSION=^2.1.2
  - CHAI_VERSION=^3.0.0
  - CHAI_VERSION=^4.0.0
script:
  - ./node_modules/.bin/if-node-version ">= 4" npm run lint
  - npm run test-travis
